apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "webcal-sync.fullname" . }}
  labels:
    {{- include "webcal-sync.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.cronjob.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.cronjob.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      backoffLimit: {{ .Values.cronjob.backoffLimit }}
      template:
        metadata:
          {{- with .Values.podAnnotations }}
          annotations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          labels:
            {{- include "webcal-sync.selectorLabels" . | nindent 12 }}
        spec:
          {{- with .Values.podSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          restartPolicy: {{ .Values.cronjob.restartPolicy }}
          containers:
          - name: webcal-sync
            {{- with .Values.securityContext }}
            securityContext:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            image: {{ include "webcal-sync.image" . }}
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
            - name: HEALTHCHECK_URL
              value: {{ .Values.healthcheckUrl | quote }}
            {{- with .Values.resources }}
            resources:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            {{- if or .Values.persistence.enabled .Values.hostPath.enabled }}
            volumeMounts:
            - name: config
              mountPath: {{ .Values.persistence.mountPath }}
            {{- end }}
          {{- if or .Values.persistence.enabled .Values.hostPath.enabled }}
          volumes:
          - name: config
            {{- if .Values.hostPath.enabled }}
            hostPath:
              path: {{ .Values.hostPath.path }}
              type: DirectoryOrCreate
            {{- else }}
            persistentVolumeClaim:
              claimName: {{ include "webcal-sync.pvcName" . }}
            {{- end }}
          {{- end }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 12 }}
          {{- end }}
