name: Publish Release Binary
on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: ["linux", "darwin"]
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.19
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: amd64
